// Mocks generated by Mockito 5.4.6 from annotations
// in nusa_chat/test/helper/mock_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i13;

import 'package:dartz/dartz.dart' as _i12;
import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i14;
import 'package:dio/src/dio_mixin.dart' as _i3;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:nusa_chat/src/core/error/failure.dart' as _i23;
import 'package:nusa_chat/src/core/service/network_info.dart' as _i15;
import 'package:nusa_chat/src/features/data/data_sources/chat_local_data_source.dart' as _i21;
import 'package:nusa_chat/src/features/data/data_sources/chat_remote_data_source.dart' as _i16;
import 'package:nusa_chat/src/features/data/data_sources/chat_socket_data_source.dart' as _i20;
import 'package:nusa_chat/src/features/data/models/media/upload_media_response.dart' as _i11;
import 'package:nusa_chat/src/features/data/models/message/list_message_response.dart' as _i9;
import 'package:nusa_chat/src/features/data/models/message/send_message_body.dart' as _i18;
import 'package:nusa_chat/src/features/data/models/message/send_message_response.dart' as _i10;
import 'package:nusa_chat/src/features/data/models/session/session_body.dart' as _i17;
import 'package:nusa_chat/src/features/data/models/session/session_response.dart' as _i8;
import 'package:nusa_chat/src/features/domain/entities/chat_attachment.dart' as _i27;
import 'package:nusa_chat/src/features/domain/entities/chat_message.dart' as _i25;
import 'package:nusa_chat/src/features/domain/entities/chat_session.dart' as _i24;
import 'package:nusa_chat/src/features/domain/entities/chat_socket_event.dart' as _i26;
import 'package:nusa_chat/src/features/domain/repositories/chat/chat_repository.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeInterceptors_1 extends _i1.SmartFake implements _i3.Interceptors {
  _FakeInterceptors_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSessionResponse_6 extends _i1.SmartFake implements _i8.SessionResponse {
  _FakeSessionResponse_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeListMessageResponse_7 extends _i1.SmartFake implements _i9.ListMessageResponse {
  _FakeListMessageResponse_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSendMessageResponse_8 extends _i1.SmartFake implements _i10.SendMessageResponse {
  _FakeSendMessageResponse_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUploadMediaResponse_9 extends _i1.SmartFake implements _i11.UploadMediaResponse {
  _FakeUploadMediaResponse_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeEither_10<L, R> extends _i1.SmartFake implements _i12.Either<L, R> {
  _FakeEither_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
            returnValueForMissingStub: _FakeBaseOptions_0(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i3.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_1(this, Invocation.getter(#interceptors)),
            returnValueForMissingStub: _FakeInterceptors_1(this, Invocation.getter(#interceptors)),
          )
          as _i3.Interceptors);

  @override
  _i4.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_2(this, Invocation.getter(#httpClientAdapter)),
            returnValueForMissingStub: _FakeHttpClientAdapter_2(this, Invocation.getter(#httpClientAdapter)),
          )
          as _i4.HttpClientAdapter);

  @override
  _i5.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_3(this, Invocation.getter(#transformer)),
            returnValueForMissingStub: _FakeTransformer_3(this, Invocation.getter(#transformer)),
          )
          as _i5.Transformer);

  @override
  set options(_i2.BaseOptions? value) =>
      super.noSuchMethod(Invocation.setter(#options, value), returnValueForMissingStub: null);

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? value) =>
      super.noSuchMethod(Invocation.setter(#httpClientAdapter, value), returnValueForMissingStub: null);

  @override
  set transformer(_i5.Transformer? value) =>
      super.noSuchMethod(Invocation.setter(#transformer, value), returnValueForMissingStub: null);

  @override
  void close({bool? force = false}) =>
      super.noSuchMethod(Invocation.method(#close, [], {#force: force}), returnValueForMissingStub: null);

  @override
  _i13.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#headUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#headUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#headUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken, #onReceiveProgress: onReceiveProgress},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken, #onReceiveProgress: onReceiveProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken, #onReceiveProgress: onReceiveProgress},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#data: data, #queryParameters: queryParameters, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#deleteUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#deleteUri, [uri], {#data: data, #options: options, #cancelToken: cancelToken}),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> query<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #query,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #query,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> queryUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #queryUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #queryUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i14.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i14.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i14.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i14.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(this, Invocation.method(#fetch, [requestOptions])),
            ),
            returnValueForMissingStub: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(this, Invocation.method(#fetch, [requestOptions])),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i3.Interceptors? interceptors,
    _i4.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
            returnValueForMissingStub: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i7.Dio);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i15.NetworkInfo {
  @override
  _i13.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock implements _i16.ChatRemoteDataSource {
  @override
  _i13.Future<_i8.SessionResponse> createSession(_i17.SessionBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [body]),
            returnValue: _i13.Future<_i8.SessionResponse>.value(
              _FakeSessionResponse_6(this, Invocation.method(#createSession, [body])),
            ),
            returnValueForMissingStub: _i13.Future<_i8.SessionResponse>.value(
              _FakeSessionResponse_6(this, Invocation.method(#createSession, [body])),
            ),
          )
          as _i13.Future<_i8.SessionResponse>);

  @override
  _i13.Future<_i9.ListMessageResponse> getMessages(String? conversationId, {DateTime? since}) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId], {#since: since}),
            returnValue: _i13.Future<_i9.ListMessageResponse>.value(
              _FakeListMessageResponse_7(this, Invocation.method(#getMessages, [conversationId], {#since: since})),
            ),
            returnValueForMissingStub: _i13.Future<_i9.ListMessageResponse>.value(
              _FakeListMessageResponse_7(this, Invocation.method(#getMessages, [conversationId], {#since: since})),
            ),
          )
          as _i13.Future<_i9.ListMessageResponse>);

  @override
  _i13.Future<_i10.SendMessageResponse> sendMessage(String? conversationId, _i18.SendMessageBody? body) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [conversationId, body]),
            returnValue: _i13.Future<_i10.SendMessageResponse>.value(
              _FakeSendMessageResponse_8(this, Invocation.method(#sendMessage, [conversationId, body])),
            ),
            returnValueForMissingStub: _i13.Future<_i10.SendMessageResponse>.value(
              _FakeSendMessageResponse_8(this, Invocation.method(#sendMessage, [conversationId, body])),
            ),
          )
          as _i13.Future<_i10.SendMessageResponse>);

  @override
  _i13.Future<_i11.UploadMediaResponse> uploadMedia({
    required String? path,
    required String? fileName,
    required String? mimeType,
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMedia, [], {
              #path: path,
              #fileName: fileName,
              #mimeType: mimeType,
              #onSendProgress: onSendProgress,
            }),
            returnValue: _i13.Future<_i11.UploadMediaResponse>.value(
              _FakeUploadMediaResponse_9(
                this,
                Invocation.method(#uploadMedia, [], {
                  #path: path,
                  #fileName: fileName,
                  #mimeType: mimeType,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i11.UploadMediaResponse>.value(
              _FakeUploadMediaResponse_9(
                this,
                Invocation.method(#uploadMedia, [], {
                  #path: path,
                  #fileName: fileName,
                  #mimeType: mimeType,
                  #onSendProgress: onSendProgress,
                }),
              ),
            ),
          )
          as _i13.Future<_i11.UploadMediaResponse>);

  @override
  String mediaUrl(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#mediaUrl, [mediaId]),
            returnValue: _i19.dummyValue<String>(this, Invocation.method(#mediaUrl, [mediaId])),
            returnValueForMissingStub: _i19.dummyValue<String>(this, Invocation.method(#mediaUrl, [mediaId])),
          )
          as String);
}

/// A class which mocks [ChatSocketDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSocketDataSource extends _i1.Mock implements _i20.ChatSocketDataSource {
  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false, returnValueForMissingStub: false) as bool);

  @override
  _i13.Stream<_i20.SocketFrame> connect(Uri? uri, {required String? origin}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [uri], {#origin: origin}),
            returnValue: _i13.Stream<_i20.SocketFrame>.empty(),
            returnValueForMissingStub: _i13.Stream<_i20.SocketFrame>.empty(),
          )
          as _i13.Stream<_i20.SocketFrame>);

  @override
  void send(_i18.SendMessageBody? body) =>
      super.noSuchMethod(Invocation.method(#send, [body]), returnValueForMissingStub: null);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ChatLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatLocalDataSource extends _i1.Mock implements _i21.ChatLocalDataSource {
  @override
  _i13.Future<String?> getVisitorId(String? websiteId) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitorId, [websiteId]),
            returnValue: _i13.Future<String?>.value(),
            returnValueForMissingStub: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<void> saveVisitorId(String? websiteId, String? visitorId) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitorId, [websiteId, visitorId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String?> getConversationId(String? websiteId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationId, [websiteId]),
            returnValue: _i13.Future<String?>.value(),
            returnValueForMissingStub: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<void> saveConversationId(String? websiteId, String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#saveConversationId, [websiteId, conversationId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> clear(String? websiteId) =>
      (super.noSuchMethod(
            Invocation.method(#clear, [websiteId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i22.ChatRepository {
  @override
  _i13.Future<_i12.Either<_i23.Failure, _i24.ChatSession>> startSession() =>
      (super.noSuchMethod(
            Invocation.method(#startSession, []),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, _i24.ChatSession>>.value(
              _FakeEither_10<_i23.Failure, _i24.ChatSession>(this, Invocation.method(#startSession, [])),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, _i24.ChatSession>>.value(
              _FakeEither_10<_i23.Failure, _i24.ChatSession>(this, Invocation.method(#startSession, [])),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, _i24.ChatSession>>);

  @override
  _i13.Future<_i12.Either<_i23.Failure, List<_i25.ChatMessage>>> getMessages(
    _i24.ChatSession? session, {
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [session], {#since: since}),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, List<_i25.ChatMessage>>>.value(
              _FakeEither_10<_i23.Failure, List<_i25.ChatMessage>>(
                this,
                Invocation.method(#getMessages, [session], {#since: since}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, List<_i25.ChatMessage>>>.value(
              _FakeEither_10<_i23.Failure, List<_i25.ChatMessage>>(
                this,
                Invocation.method(#getMessages, [session], {#since: since}),
              ),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, List<_i25.ChatMessage>>>);

  @override
  _i13.Stream<_i26.ChatSocketEvent> connect(_i24.ChatSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [session]),
            returnValue: _i13.Stream<_i26.ChatSocketEvent>.empty(),
            returnValueForMissingStub: _i13.Stream<_i26.ChatSocketEvent>.empty(),
          )
          as _i13.Stream<_i26.ChatSocketEvent>);

  @override
  _i13.Future<_i12.Either<_i23.Failure, String?>> sendText(_i24.ChatSession? session, String? text) =>
      (super.noSuchMethod(
            Invocation.method(#sendText, [session, text]),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(this, Invocation.method(#sendText, [session, text])),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(this, Invocation.method(#sendText, [session, text])),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, String?>>);

  @override
  _i13.Future<_i12.Either<_i23.Failure, _i27.UploadedMedia>> uploadMedia(
    _i27.ChatAttachment? attachment, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMedia, [attachment], {#onProgress: onProgress}),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, _i27.UploadedMedia>>.value(
              _FakeEither_10<_i23.Failure, _i27.UploadedMedia>(
                this,
                Invocation.method(#uploadMedia, [attachment], {#onProgress: onProgress}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, _i27.UploadedMedia>>.value(
              _FakeEither_10<_i23.Failure, _i27.UploadedMedia>(
                this,
                Invocation.method(#uploadMedia, [attachment], {#onProgress: onProgress}),
              ),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, _i27.UploadedMedia>>);

  @override
  _i13.Future<_i12.Either<_i23.Failure, String?>> sendMedia(
    _i24.ChatSession? session,
    _i27.UploadedMedia? media, {
    String? caption = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMedia, [session, media], {#caption: caption}),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(
                this,
                Invocation.method(#sendMedia, [session, media], {#caption: caption}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(
                this,
                Invocation.method(#sendMedia, [session, media], {#caption: caption}),
              ),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, String?>>);

  @override
  _i13.Future<_i12.Either<_i23.Failure, String?>> sendLocation(
    _i24.ChatSession? session,
    _i25.ChatLocation? location,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendLocation, [session, location]),
            returnValue: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(this, Invocation.method(#sendLocation, [session, location])),
            ),
            returnValueForMissingStub: _i13.Future<_i12.Either<_i23.Failure, String?>>.value(
              _FakeEither_10<_i23.Failure, String?>(this, Invocation.method(#sendLocation, [session, location])),
            ),
          )
          as _i13.Future<_i12.Either<_i23.Failure, String?>>);

  @override
  String mediaUrl(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#mediaUrl, [mediaId]),
            returnValue: _i19.dummyValue<String>(this, Invocation.method(#mediaUrl, [mediaId])),
            returnValueForMissingStub: _i19.dummyValue<String>(this, Invocation.method(#mediaUrl, [mediaId])),
          )
          as String);

  @override
  _i13.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}
