// Generates lib/src/core/util/emoji/emoji_data.dart from the Unicode emoji
// list and the CLDR annotations (Indonesian + English) used for search.
//
//   curl -LO https://unicode.org/Public/emoji/15.1/emoji-test.txt
//   curl -L -o id.xml https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotations/id.xml
//   curl -L -o id-derived.xml https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotationsDerived/id.xml
//   curl -L -o en.xml https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotations/en.xml
//   curl -L -o en-derived.xml https://raw.githubusercontent.com/unicode-org/cldr/main/common/annotationsDerived/en.xml
//   dart run tool/generate_emoji_data.dart <folder with those files>
//
// Only fully-qualified emoji up to [maxVersion] are kept, so phones with an
// older system emoji font do not show empty boxes; skin-tone variants are
// left out.
import 'dart:io';

const maxVersion = 13.0;

/// Unicode group → the Figma tab it belongs to (the design has 8 tabs, so
/// symbols and flags share the objects tab).
const groups = {
  'Smileys & Emotion': 'smileys',
  'People & Body': 'people',
  'Animals & Nature': 'animals',
  'Food & Drink': 'food',
  'Activities': 'activities',
  'Travel & Places': 'travel',
  'Objects': 'objects',
  'Symbols': 'objects',
  'Flags': 'objects',
};

const output = 'lib/src/core/util/emoji/emoji_data.dart';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/generate_emoji_data.dart <data folder>');
    exit(64);
  }
  final dir = args.first;
  final names = <String, List<String>>{};
  for (final file in ['id.xml', 'id-derived.xml', 'en.xml', 'en-derived.xml']) {
    final path = '$dir/$file';
    if (File(path).existsSync()) _readAnnotations(File(path).readAsStringSync(), names);
  }

  final byCategory = <String, List<String>>{for (final c in groups.values) c: []};
  String? category;
  final line = RegExp(r'^([0-9A-F ]+?)\s*; fully-qualified\s*# (\S+) E(\d+\.\d+) (.+)$');
  for (final raw in File('$dir/emoji-test.txt').readAsLinesSync()) {
    if (raw.startsWith('# group: ')) {
      category = groups[raw.substring(9).trim()];
      continue;
    }
    final match = line.firstMatch(raw);
    if (match == null || category == null) continue;
    final codes = match.group(1)!.split(' ').map((c) => int.parse(c, radix: 16)).toList();
    if (codes.any((c) => c >= 0x1F3FB && c <= 0x1F3FF)) continue;
    if (double.parse(match.group(3)!) > maxVersion) continue;

    final emoji = String.fromCharCodes(codes);
    final key = String.fromCharCodes(codes.where((c) => c != 0xFE0F));
    final words = <String>{...?names[key], match.group(4)!.toLowerCase()};
    byCategory[category]!.add("NusaChatEmoji('$emoji', '${_escape(words.join('|'))}')");
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_emoji_data.dart — do not edit.')
    ..writeln('// Unicode emoji-test.txt + CLDR annotations (id, en), Emoji <= $maxVersion.')
    ..writeln()
    ..writeln("import 'package:nusa_chat/src/core/util/emoji/emoji.dart';")
    ..writeln()
    ..writeln('const nusaChatEmojiData = <NusaChatEmojiCategory, List<NusaChatEmoji>>{');
  for (final entry in byCategory.entries) {
    buffer.writeln('  NusaChatEmojiCategory.${entry.key}: [');
    for (final emoji in entry.value) {
      buffer.writeln('    $emoji,');
    }
    buffer.writeln('  ],');
  }
  buffer.writeln('};');
  File(output).writeAsStringSync(buffer.toString());
  final total = byCategory.values.fold<int>(0, (sum, list) => sum + list.length);
  stdout.writeln('Wrote $total emoji to $output');
}

/// Collects the name and keywords of every `<annotation cp="…">`, lowercased.
void _readAnnotations(String xml, Map<String, List<String>> names) {
  final annotation = RegExp(r'<annotation cp="([^"]+)"( type="tts")?>([^<]*)</annotation>');
  for (final match in annotation.allMatches(xml)) {
    final words = match
        .group(3)!
        .split('|')
        .map((w) => _unescapeXml(w.trim().toLowerCase()))
        .where((w) => w.isNotEmpty);
    (names[_unescapeXml(match.group(1)!)] ??= []).addAll(words);
  }
}

String _unescapeXml(String s) => s
    .replaceAll('&amp;', '&')
    .replaceAll('&quot;', '"')
    .replaceAll('&apos;', "'")
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>');

String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
